.PHONY: deploy

CLOUD_RUN_FLAGS ?= --no-invoker-iam-check
# Set by CI (job env); all passed to Cloud Run. APP_ENV, WhatsApp, and Attio vars.
APP_ENV ?=
WHATS_APP_TOKEN ?=
WHATSAPP_PHONE_NUMBER_ID ?=
ATTIO_API_KEY_DEV ?=
ATTIO_API_KEY_PROD ?=
ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV ?=
ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD ?=
ATTIO_WORKSPACE_MEMBER_ID_DEV ?=
ATTIO_WORKSPACE_MEMBER_ID_PROD ?=

# Comma-separated KEY=VALUE for gcloud. Do not use commas in secret values.
CLOUD_RUN_ENV_VARS = APP_ENV=$(APP_ENV),WHATS_APP_TOKEN=$(WHATS_APP_TOKEN),WHATSAPP_PHONE_NUMBER_ID=$(WHATSAPP_PHONE_NUMBER_ID),ATTIO_API_KEY_DEV=$(ATTIO_API_KEY_DEV),ATTIO_API_KEY_PROD=$(ATTIO_API_KEY_PROD),ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV=$(ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV),ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD=$(ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD),ATTIO_WORKSPACE_MEMBER_ID_DEV=$(ATTIO_WORKSPACE_MEMBER_ID_DEV),ATTIO_WORKSPACE_MEMBER_ID_PROD=$(ATTIO_WORKSPACE_MEMBER_ID_PROD)

deploy: push-image
	gcloud run deploy "$(SERVICE_NAME)" \
		--image "$(IMAGE)" \
		--region "$(REGION)" \
		--project "$(PROJECT_ID)" \
		--platform managed \
		$(if $(APP_ENV),--set-env-vars "$(CLOUD_RUN_ENV_VARS)",) \
		$(CLOUD_RUN_FLAGS)
