.PHONY: deploy

CLOUD_RUN_FLAGS ?= --no-invoker-iam-check
# Set by CI (job env). Dev workflow sets only _DEV; prod workflow sets only _PROD.
APP_ENV ?=
WHATS_APP_TOKEN ?=
WHATSAPP_PHONE_NUMBER_ID ?=
NEW_MEMBER_ADMIN_PHONE ?=
ATTIO_API_KEY_DEV ?=
ATTIO_API_KEY_PROD ?=
ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV ?=
ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD ?=
ATTIO_WORKSPACE_MEMBER_ID_DEV ?=
ATTIO_WORKSPACE_MEMBER_ID_PROD ?=

# Pass only the Attio vars for the active env (dev vs prod).
ATTIO_ENV_VARS_DEV = ATTIO_API_KEY_DEV=$(ATTIO_API_KEY_DEV),ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV=$(ATTIO_FOUNDER_LIFECYCLE_LIST_ID_DEV),ATTIO_WORKSPACE_MEMBER_ID_DEV=$(ATTIO_WORKSPACE_MEMBER_ID_DEV)
ATTIO_ENV_VARS_PROD = ATTIO_API_KEY_PROD=$(ATTIO_API_KEY_PROD),ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD=$(ATTIO_FOUNDER_LIFECYCLE_LIST_ID_PROD),ATTIO_WORKSPACE_MEMBER_ID_PROD=$(ATTIO_WORKSPACE_MEMBER_ID_PROD)
ATTIO_ENV_VARS = $(if $(filter prod,$(APP_ENV)),$(ATTIO_ENV_VARS_PROD),$(ATTIO_ENV_VARS_DEV))
CLOUD_RUN_ENV_VARS = APP_ENV=$(APP_ENV),WHATS_APP_TOKEN=$(WHATS_APP_TOKEN),WHATSAPP_PHONE_NUMBER_ID=$(WHATSAPP_PHONE_NUMBER_ID),NEW_MEMBER_ADMIN_PHONE=$(NEW_MEMBER_ADMIN_PHONE),$(ATTIO_ENV_VARS)

deploy: push-image
	gcloud run deploy "$(SERVICE_NAME)" \
		--image "$(IMAGE)" \
		--region "$(REGION)" \
		--project "$(PROJECT_ID)" \
		--platform managed \
		$(if $(APP_ENV),--set-env-vars "$(CLOUD_RUN_ENV_VARS)",) \
		$(CLOUD_RUN_FLAGS)
